name: Run tests

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
    test-php:
        name: Test on php ${{ matrix.php-version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            fail-fast: false
            matrix:
                experimental: [false]
                coverage-extension: [pcov]
                php-version: ["7.1", "7.2", "7.3", "7.4", "8.0", "8.1"]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Install pdfinfo
              run: sudo apt-get install -y poppler-utils ghostscript
            - name: Use php ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  coverage: ${{ matrix.coverage-extension }}
                  extensions: bcmath, imagick, gd
                  ini-values: display_errors=on, error_reporting=-1
            - name: List php modules
              run: php -m
            - name: List php modules using "no php ini" mode
              run: php -m -n
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install dependencies
              run: composer install --no-interaction
            - name: Disable ImageMagick Ghostscript workaround
              run: sudo sed -i '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml
            - name: Run php tests
              run: ./vendor/bin/phpunit
